config/routes.rb
Rails.application.routes.draw do
  post '/s', to: 'short_urls#create', as: :short_urls
  get  '/s/:short_id', to: 'short_urls#show', as: :short_url

  get   '/a/:admin_id', to: 'admin/short_urls#show',  as: :admin_short_url
  put   '/a/:admin_id', to: 'admin/short_urls#update'
  patch '/a/:admin_id', to: 'admin/short_urls#update'

  root "short_urls#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
    validates :origin_url, presence: true, url: true

    before_create :generate_short_id, :generate_admin_id

    def visit
        increment!(:count) unless expired?
    end

    def expired?
        self.expires_at && DateTime.current > self.expires_at
    end

    private
    def generate_short_id
        self.short_id = SecureRandom.hex (3)
    end

    def generate_admin_id
        self.admin_id = SecureRandom.hex (10)
    end
end

app/controllers/admin/short_urls_controller.rb
class Admin::ShortUrlsController < ApplicationController
  before_action :set_short_url
  def show
  end

  def update
    if @short_url.update(short_url_params)
      redirect_to admin_short_url_path(admin_id: @short_url.admin_id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def set_short_url
    @short_url = ShortUrl.find_by(admin_id: params[:admin_id])
  end

  def short_url_params
    params.require(:short_url).permit(:expires_at)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController

  def show
    @short_url = ShortUrl.find_by(short_id: params[:short_id])

    if @short_url && !@short_url.expired?
      @short_url.visit
      redirect_to @short_url.origin_url
    else
      render :file => "#{Rails.root}/public/404.html",  :status => 404
    end
  end

  def new
  end

  def create
    @short_url = ShortUrl.new(short_url_params)

    if @short_url.save
      render partial: 'short_url', locals: { short_url: @short_url }, status: :ok
    else
      render partial: 'error', locals: { short_url: @short_url }, status: :bad_request
    end
  end

  private
  def short_url_params
    params.require(:short_url).permit(:origin_url)
  end
end

app/helpers/admin/short_urls_helper.rb
module Admin::ShortUrlsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/views/admin/short_urls/show.html.erb
<p>
  <strong>Short url:</strong>
  <%= link_to short_url_url(short_id: @short_url.short_id), short_url_url(short_id: @short_url.short_id) %>
</p>

<p>
  <strong>Origin url:</strong> <%= @short_url.origin_url %>
</p>

<p>
  <strong>Admin url:</strong>
  <%= link_to admin_short_url_url(admin_id: @short_url.admin_id), admin_short_url_url(admin_id: @short_url.admin_id) %>
</p>

<p>
  <strong>Count:</strong> <%= @short_url.count %>
</p>

<p>
  <strong>Current time:</strong>
  <%= DateTime.current.utc %>
</p>

<p>
  <strong>Expired at:</strong>
  <%= @short_url.expires_at %>
</p>

<%= form_with(model: @short_url, url: admin_short_url_path(admin_id: @short_url.admin_id)) do |form| %>
  <% if @short_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@short_url.errors.count, "error") %> prohibited this short_url from being saved:</h2>

      <ul>
        <% @short_url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :expires_at %>
    <%= form.datetime_local_field :expires_at %>
  </div>

  <div class="actions">
    <%= form.submit 'Update expires at' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortUrlDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/short_urls/_error.html.erb
<% short_url.errors.full_messages.each do |error| %>
    <li><%= error %></li>
<% end %>

app/views/short_urls/_form.html.erb
<%= form_with(model: ShortUrl.new, data: { type: "html", action: "ajax:success->short-urls#onCreateSuccess ajax:error->short-urls#onCreateError" }) do |form| %>

  <div class="field">
    <%= form.label :origin_url %>
    <%= form.text_field :origin_url, data: { 'short-urls-target': "originUrl" } %>
  </div>

  <div class="actions">
    <%= form.submit "Create" %>
  </div>
<% end %>

app/views/short_urls/_short_url.html.erb
<li>
    <p>
        <strong>Short url:</strong>
        <%= link_to short_url_url(short_id: short_url.short_id), short_url_url(short_id: short_url.short_id) %>
    </p>

    <p>
        <strong>Origin url:</strong> <%= short_url.origin_url %>
    </p>

    <p>
        <strong>Admin url:</strong>
        <%= link_to admin_short_url_url(admin_id: short_url.admin_id), admin_short_url_url(admin_id: short_url.admin_id) %>
    </p>

</li>

app/views/short_urls/new.html.erb
<h1>New Short Url</h1>

<div data-controller="short-urls">
    <ul data-short-urls-target="shortUrlErrors"></ul>
    <%= render 'form'%>
    <ul data-short-urls-target="shortUrlList">
    </ul>
</div>